name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - 'start.sh'
  pull_request:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - 'start.sh'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create minimal build context
        run: |
          mkdir -p ./docker-build-context
          cp Dockerfile start.sh ./docker-build-context/

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./docker-build-context 
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/hubproxy:latest
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.description=hubproxy
          cache-from: type=gha
          cache-to: type=gha,mode=max
